apiVersion: v1
kind: ServiceAccount
metadata:
  name: fuzzy-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fuzzy-proxy
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fuzzy-proxy-binding
subjects:
- kind: ServiceAccount
  name: fuzzy-proxy
roleRef:
  kind: Role
  name: fuzzy-proxy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: fuzzy-proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-fuzzy-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuzzy-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-fuzzy-proxy
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-fuzzy-proxy
    spec:
      containers:
      - name: fuzzy-proxy
        image: maayanlab/fuzzy-proxy:1.2.5
        imagePullPolicy: IfNotPresent
        tty: true
        env:
        - name: KUBE_NAMESPACE
          value: default
      restartPolicy: Always
      serviceAccount: fuzzy-proxy